# Generated by Django 5.0.14 on 2025-07-26 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.TextField()),
                ('direccion', models.TextField()),
                ('fecha_registro', models.DateField()),
                ('tipo_documento', models.TextField(blank=True, null=True)),
                ('numero_documento', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.TextField()),
                ('pais', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'destino',
            },
        ),
        migrations.CreateModel(
            name='PaqueteTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paquete', models.TextField()),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_dias', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_paquete', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='paquetes/')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.destino')),
            ],
            options={
                'db_table': 'paquetes_turisticos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('estado_reserva', models.TextField()),
                ('total_reserva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paqueteturistico')),
            ],
        ),
    ]
